features:
- name: glycohemoglobin
  source: LBXGH
  file: GHB_I
  type: numerical
  role: target
  drop_extrema: true
  log_transform: false
  unit: percent
- name: hdl_cholesterol
  source: LBDHDD
  file: HDL_I
  type: numeric
  role: target
  drop_extrema: true
  log_transform: false
  unit: mg/dL
- name: bmi
  source: BMXBMI
  file: BMX_I
  type: numeric
  role: feature
  drop_extrema: true
  log_transform: false
  unit: "kg/m\xB2"
- name: daily_sugar
  source: DR1TSUGR
  file: DR1TOT_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: g
- name: weekly_hrs_worked
  source: OCQ180
  file: OCQ_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: hours
- name: daily_total_fat
  source: DR1TTFAT
  file: DR1TOT_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: g
- name: albumin
  source: URXUMA
  file: ALB_CR_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: ug/mL
- name: daily_sedentary_activity
  source: PAD680
  file: PAQ_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: minutes
- name: daily_calories
  source: DR1TKCAL
  file: DR1TOT_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: kcal
- name: age
  source: RIDAGEYR
  file: DEMO_I
  type: numeric
  role: feature
  drop_extrema: true
  log_transform: false
  unit: years
- name: monthly_family_income
  source: IND235
  file: INQ_I
  type: categorical
  role: feature
