features:
- name: glycohemoglobin
  source: LBXGH
  file: GHB_I
  type: numerical
  role: target
  drop_extrema: true
  log_transform: false
  unit: percent
- name: hdl_cholesterol
  source: LBDHDD
  file: HDL_I
  type: numeric
  role: target
  drop_extrema: true
  log_transform: false
  unit: mg/dL
- name: daily_sedentary_activity
  source: PAD680
  file: PAQ_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: minutes
- name: daily_total_fat
  source: DR1TTFAT
  file: DR1TOT_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: g
- name: ever_smoked_100
  source: SMQ020
  file: SMQ_I
  type: categorical
  role: feature
- name: weekly_hrs_worked
  source: OCQ180
  file: OCQ_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: hours
- name: systolic_bp
  source: BPXSY1
  file: BPX_I
  type: numeric
  role: feature
  drop_extrema: true
  log_transform: false
  unit: mmHg
- name: hydroxyvitamin_d2_d3
  source: LBXVIDMS
  file: VID_I
  type: numerical
  role: feature
  drop_extrema: true
  log_transform: false
  unit: nmol/L
- name: age
  source: RIDAGEYR
  file: DEMO_I
  type: numeric
  role: feature
  drop_extrema: true
  log_transform: false
  unit: years
- name: bmi
  source: BMXBMI
  file: BMX_I
  type: numeric
  role: feature
  drop_extrema: true
  log_transform: false
  unit: "kg/m\xB2"
- name: drinks_per_day
  source: ALQ130
  file: ALQ_I
  type: numeric
  role: feature
  drop_extrema: true
  log_transform: false
  unit: drinks
- name: waist_circumference
  source: BMXWAIST
  file: BMX_I
  type: numeric
  role: feature
  drop_extrema: true
  log_transform: false
  unit: cm
